### ISSUE TITLE
SqlAlchemy ORM?

### ISSUE THREAD

**Issue by Waym1ng** [CoderCharm/MallAPI#4]
本来想学习一下FastAPi配合SqlAlchemy怎么使用的 还有数据库迁移的问题 感觉网上资源比较少 结果博主选择直接撸sql了 难道我也要放弃了吗 博主有demo学习一下吗？感谢~

**Comment by wxy2077** [comment]
我这个后台管理的项目就是，你可以参考一下 https://github.com/CoderCharm/FastAdmin

**Comment by wxy2077** [comment]
我今天总结使用FastAPI的经验，写了一个fastapi+mysql的项目生成器，里面使用SqlAlchemy ORM迁移，也有具体的使用orm CRUD操作，你可以参考 https://github.com/CoderCharm/fastapi-mysql-generator 加油老哥！！学习要有动力。

**Comment by Waym1ng** [comment]
非常感谢老哥！！我按照你FastAdmin 迁移成功了 并且ORM查询也没问题了 但是我有个问题哦
![image](https://user-images.githubusercontent.com/49272616/96238748-64e14b00-0fd1-11eb-9a9d-e78608eb9173.png)
你FastAdmin项目中 这里的导入是不是有问题 改成了在外一层的包 再迁移才能成功
https://www.charmcode.cn/article/2020-07-12_FastAPI_SqlAlchemy_mysql_alembic 找到了您博客的这篇文章，thanks！！

**Comment by wxy2077** [comment]
红框标的地方，是因为路径问题，这个地方取决于你倒入 orm models路径是否正确。 所以有上面的 `sys.path.insert(0, BASE_DIR)`这样一句话。
